name: Build Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git nasm build-essential qemu gdb
        version: 1.0
    - name: make
      run: make
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: xv6.img
        path: ${{github.workspace}}/xv6.img
